hi! link goFuncBlock Identifier
hi! link goDeclNames Identifier
hi! link goPackageName goDeclNames
hi! link goTypeDeclName goDeclNames
hi! link goFuncName goDeclNames
hi! link goImportItem Identifier
hi! link goImportedPackages Identifier
hi! link goStructLiteralBlock Identifier
hi! link goCurrentPackage Identifier
