#!/usr/bin/env sh

ln -s $PWD/vimrc $HOME/.vimrc

mkdir -p $HOME/.vim/pack/vim-go/start
git clone https://github.com/fatih/vim-go.git $HOME/.vim/pack/vim-go/start/vim-go

mkdir -p $HOME/.vim/pack/ctrl-p/start
git clone https://github.com/kien/ctrlp.vim.git $HOME/.vim/pack/ctrl-p/start/ctrl-p

# add clang_complete

# add mucomplete
