#!/usr/bin/env sh

ln -s $PWD/vimrc $HOME/.vimrc

# dracula
mkdir -p $HOME/.vim/pack/dracula/start
git clone https://github.com/dracula/vim.git $HOME/.vim/pack/dracula/start/dracula

# vim-go
mkdir -p $HOME/.vim/pack/vim-go/start
git clone https://github.com/fatih/vim-go.git $HOME/.vim/pack/vim-go/start/vim-go

# ctrl-p
mkdir -p $HOME/.vim/pack/ctrl-p/start
git clone https://github.com/kien/ctrlp.vim.git $HOME/.vim/pack/ctrl-p/start/ctrl-p

# add clang_complete

# add mucomplete
mkdir -p $HOME/.vim/pack/mucomplete/start
git clone https://github.com/lifepillar/vim-mucomplete.git $HOME/.vim/pack/mucomplete/start/mucomplete
