#! /bin/sh

xrandr --output HDMI-0 --right-of DP-0

xsetroot -solid \#008080
xsetroot -cursor_name left_ptr

polybar left -c $HOME/.config/polybar/config.ini &
polybar right -c $HOME/.config/polybar/config.ini &

rofi &
sxhkd &

pasystray &
nm-applet &
blueman-applet &

bspc monitor HDMI-0 -d 1 2 3 q w e a s d
bspc monitor DP-0 -d 1 2 3 q w e a s d

bspc config pointer_follows_focus true

bspc config border_width         2
#bspc config window_gap          12
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc rule -a minecraft-launcher state=floating
